language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.9.0
  
notifications:
  email: false

services:
  - postgresql

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - psql -c 'create table users (id serial primary key, firstName varchar(30), lastName varchar(30), email varchar(50), password varchar(255), gender varchar(11), jobRole varchar(50), department varchar(50), address varchar(30));' -U postgres